### ISSUE TITLE
several crash wallet

### ISSUE THREAD

**Issue by stanxii** [KyberNetwork/KyberWallet#63]
When i testing wallet, several minutes, Web will crash.

**Comment by tranvictor** [comment]
@stanxii also for this issue, browser and os info is helpful for us.

**Comment by stanxii** [comment]
chrome 版本 60.0.3112.90（正式版本） （64 位）
Os win7 64bit

**Comment by whyka** [comment]
I have the same issue in Windows and Mac OS X. Working on it.

**Comment by whyka** [comment]
Also crash on Chrome latest Version 60.0.3112.101 (Official Build) (64-bit).

**Comment by stanxii** [comment]
@whyka  Great work,  thanks for resolve issue so fast.

**Comment by andrewsource** [comment]
@whyka It still crash in my chrome. My environment is as the same as stanxil.

**Comment by whyka** [comment]
@andrewsource I see. Seem it only fixed on Mac OS X. Let's me investigate more on Windows.

**Comment by tranvictor** [comment]
@whyka more info for you, my Chrome 60 on Mac was crashing constantly and then suddenly it was not crashing anymore without any browser update or wallet update. So it doesn't always crash.

One of my best bets on this is that Chrome 60 has some flaws (or features) that would crash when React's virtual DOM is being updated in high frequency. We update the wallet quite frequently. The updater is trigger each 10s (or block time if the node supports `filter`) and does element 10-15 updates as fast as it can.

**Comment by andrewsource** [comment]
@tranvictor I've tested chrome with different versions in my windows 7 OS, and here is results:
- 46.0.2490.80 **64 bit**: no crash
- 47.0.2526.73 **32 bit**: no crash
- 59.0.3071.115 **64 bit**: no crash
- 60.0.3112.101 **64bit** (lastest build): crash

I also think of that Chrome 60 have flaws.

**Comment by whyka** [comment]
After searching, neither I saw similar report nor issue in React project.
I don't think this is flaw of Chrome 60 but stricter in resource management.
Actually, my PR #71  fixed crash in the case fresh open and no wallet yet, both Windows and Mac OS X. It's crash again when you create or import wallet.
My current direction is investigating more on React/Redux best practices and implementations of Kyber components.

**Comment by whyka** [comment]
@tranvictor 10 second update is not a big deal though. I've seen React app that much frequently update than that, such as https://cryptowat.ch/

**Comment by tranvictor** [comment]
Maybe both that Chrome has something strange and we do not follow best practices. Race condition is one possible thing to concern.

@andrewsource can you also test the wallet with no accounts nor wallets on those browsers to see if you see the same thing with @whyka ?

@whyka one thing you can try is to disable all of the updates. I myself disabled all of them before to test but no luck.

**Comment by tranvictor** [comment]
@stanxii we have just deployed a patch to this issue, can you please try again and tell us if it really fixes the crashing problem? Thanks.

**Comment by whyka** [comment]
Still crash if open dialog Exchange and input some amount. Happens on both Windows and Mac OS X.

**Comment by andrewsource** [comment]
@whyka Could you describe details steps causing crash? I also input amount in Exchange form, but there is no crash in my Chrome (Windows)

**Comment by whyka** [comment]
@andrewsource You can try this:
Click Exchange to open Quick Exchange.
In field "Exchange", choose GNT.
In field "Expected to receive", choose ETH.
Input some amount and wait.

I have a screen record if you need. I tried on Windows too.

**Comment by tranvictor** [comment]
@whyka lets go ahead and upload the video. It is even better if you can find a root cause of that.

@andrewsource i still don't quite believe that `.toString(10)` is the reason. I read their implementation and it has nothing that I can suspect. But yeah, somehow it crashes much less!

**Comment by whyka** [comment]
I upload video here https://drive.google.com/open?id=0B7ltVC8U1G-YdVk1Qk9EeXpHZzQ

**Comment by andrewsource** [comment]
@whyka, @tranvictor  When change value quickly, the onChange events are fired, and it calls function BigNumber.toString(10) many times so it causes crash. I also change other functions, which have .toString(10) (to .toString()) and the crash does not happen, at least in my computer. 
I'm still finding the root cause
